# Site settings
title: Harbourside Wellness Center
email: contactus@harboursidewellness.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: # the base hostname & protocol for your site

# User setting
owner: Harbourside Wellness Center
email: contactus@harboursidewellness.com
facebook_username: Harbourside-Wellness-Center-1074081175971947/
#twitter_username:
#github_username:
address:
  - line: 123 Main Street
  - line: Jupiter, FL
  # Feel free to add more lines here
telephone: 888-111-2222
copyright:

# API settings
#google_api_key:

# Build settings
markdown: kramdown
